"""Auto-generated by corpus2skill.py (Phase 3).

Theme: FastAPI dependency injection patterns
Source chunks: 3
Source URLs:
- https://fastapi.tiangolo.com/tutorial/dependencies/
Generated: 2026-05-31T20:58:04
Model: deepseek-r1:14b

Do not edit by hand; rerun corpus2skill.py to regenerate.
"""

"""
Helper module for FastAPI dependency injection patterns.

This module provides reusable functions and type aliases for common dependency injection patterns in FastAPI.
"""

from typing import Annotated, Any, Optional, Union
from fastapi import Depends


async def common_parameters(
    q: str | None = None, 
    skip: int = 0, 
    limit: int = 100
) -> dict:
    """Common query parameters for multiple endpoints.

    Args:
        q: Search term or filter.
        skip: Number of items to skip.
        limit: Maximum number of items to return.

    Returns:
        Dictionary containing the provided parameters.
    """
    return {"q": q, "skip": skip, "limit": limit}


CommonParamsDep = Annotated[dict, Depends(common_parameters)]


async def current_user(email: str) -> dict:
    """Simulate user authentication dependency.

    Args:
        email: Email of the authenticated user.

    Returns:
        Dictionary with user information.
    """
    return {"user_email": email}