"""Auto-generated by corpus2skill.py (Phase 3).

Theme: FastAPI dependency injection patterns
Source chunks: 3
Source URLs:
- https://fastapi.tiangolo.com/tutorial/dependencies/
Generated: 2026-05-31T18:06:39
Model: deepseek-r1:14b

Do not edit by hand; rerun corpus2skill.py to regenerate.
"""

"""
Helper functions for FastAPI dependency injection patterns.

This module provides reusable utilities for working with dependencies in FastAPI,
including common parameter handling and dependency stacking.
"""

from fastapi import Depends, HTTPException, status
from typing import Annotated, Any, TypeVar, Union
from collections.abc import Callable

T = TypeVar("T")

def create_common_parameters_dependency(
    q: str | None = None, 
    skip: int = 0, 
    limit: int = 100
) -> dict:
    """Create a dependency that handles common query parameters.

    Args:
        q: Search term or filter.
        skip: Number of items to skip.
        limit: Maximum number of items to return.

    Returns:
        Dictionary containing the provided parameters.
    """
    return {"q": q, "skip": skip, "limit": limit}

def AnnotatedDependency(func: Callable) -> Any:
    """Helper to create Annotated dependencies for reuse.

    This function allows creating type-annotated dependencies that can be reused
    across multiple endpoints.

    Args:
        func: The dependency function to annotate.

    Returns:
        Annotated type with the provided dependency function.
    """
    return Annotated[dict, Depends(func)]

def stack_dependencies(*dependencies: Callable) -> Any:
    """Stack multiple dependencies into a single hierarchical dependency.

    This allows creating complex dependency trees by combining multiple
    smaller dependencies.

    Args:
        *dependencies: Functions to be stacked as dependencies.

    Returns:
        Combined dependency that includes all provided functions.
    """
    return Annotated[dict, Depends([d for d in dependencies])]

__all__ = [
    "create_common_parameters_dependency",
    "AnnotatedDependency",
    "stack_dependencies"
]