"""Auto-generated by corpus2skill.py (Phase 3).

Theme: FastAPI dependency injection patterns
Source chunks: 3
Source URLs:
- https://fastapi.tiangolo.com/tutorial/dependencies/
Generated: 2026-05-31T19:40:35
Model: deepseek-r1:14b

Do not edit by hand; rerun corpus2skill.py to regenerate.
"""

"""
Helper functions for FastAPI dependency injection patterns.

This module provides utilities to simplify working with dependencies in FastAPI,
especially around creating reusable and annotated dependencies.
"""

from typing import Annotated
from fastapi import Depends


def create_shared_dependency(func: callable) -> type:
    """
    Creates a shared dependency from an async function.

    Args:
        func: The async dependency function.

    Returns:
        Type alias for the dependency with Annotated applied.
    """
    return Annotated[dict, Depends(func)]


# Example usage (executed only when module is run directly)
if __name__ == "__main__":
    from fastapi import FastAPI

    app = FastAPI()

    async def common_params(q: str | None = None):
        return {"q": q}

    CommonDep = create_shared_dependency(common_params)

    @app.get("/items")
    async def items(commons: CommonDep):
        return commons