"""Auto-generated by corpus2skill.py (Phase 3).

Theme: Kubernetes pod security standards
Source chunks: 1
Source URLs:
- https://kubernetes.io/docs/concepts/security/pod-security-standards/
Generated: 2026-06-01T01:45:28
Model: deepseek-r1:14b

Do not edit by hand; rerun corpus2skill.py to regenerate.
"""

"""
Kubernetes Pod Security Standards Helper Module

This module provides utility functions to validate pod security configurations 
against Kubernetes' recommended standards.
"""

def get_seccomp_profile_types():
    """Return the allowed seccomp profile types for pods.

    Returns:
        list: A list of valid seccomp profile type strings
    """
    return ['RuntimeDefault', 'Localhost']

def get_allowed_sysctls():
    """Return the allowed sysctl names and their minimum Kubernetes versions.

    Returns:
        dict: Mapping from sysctl name to version string indicating when it was 
            first allowed
    """
    return {
        "kernel.shm_rmid_forced": None,
        "net.ipv4.ip_local_port_range": None,
        "net.ipv4.ip_unprivileged_port_start": None,
        "net.ipv4.tcp_syncookies": None,
        "net.ipv4.ping_group_range": None,
        "net.ipv4.ip_local_reserved_ports": "1.27",
        "net.ipv4.tcp_keepalive_time": "1.29",
        "net.ipv4.tcp_fin_timeout": "1.29",
        "net.ipv4.tcp_keepalive_intvl": "1.29",
        "net.ipv4.tcp_keepalive_probes": "1.29"
    }

if __name__ == "__main__":
    pass  # Example usage can be placed here if needed