"""Auto-generated by corpus2skill.py (Phase 3).

Theme: Kubernetes pod security standards
Source chunks: 1
Source URLs:
- https://kubernetes.io/docs/concepts/security/pod-security-standards/
Generated: 2026-05-31T21:59:26
Model: deepseek-r1:14b

Do not edit by hand; rerun corpus2skill.py to regenerate.
"""

"""
This module provides helper functions for validating Kubernetes pod security standards related to seccomp profiles and sysctls.
"""

from typing import Optional, Literal, Union

SECCOMP_PROFILE_TYPES: tuple[Literal['RuntimeDefault', 'Localhost', None], ...] = (
    'RuntimeDefault',
    'Localhost',
    None,
)

def is_valid_seccomp_profile_type(seccomp_type: Optional[str]) -> bool:
    """
    Determines if a seccomp profile type is valid according to Kubernetes standards.

    Args:
        seccomp_type (Optional[str]): The seccomp profile type to validate.
            Allowed values are 'RuntimeDefault', 'Localhost', or None.

    Returns:
        bool: True if the value is valid, False otherwise.
    """
    return seccomp_type in SECCOMP_PROFILE_TYPES

ALLOWED_SYSCtls = {
    "kernel.shm_rmid_forced",
    "net.ipv4.ip_local_port_range",
    "net.ipv4.ip_unprivileged_port_start",
    "net.ipv4.tcp_syncookies",
    "net.ipv4.ping_group_range",
    "net.ipv4.ip_local_reserved_ports",
    "net.ipv4.tcp_keepalive_time",
    "net.ipv4.tcp_fin_timeout",
    "net.ipv4.tcp_keepalive_intvl",
    "net.ipv4.tcp_keepalive_probes",
}

def is_allowed_sysctl(sysctl_name: str) -> bool:
    """
    Checks if a sysctl name is allowed by Kubernetes pod security standards.

    Args:
        sysctl_name (str): The sysctl parameter to validate.

    Returns:
        bool: True if the sysctl is allowed, False otherwise.
    """
    return sysctl_name in ALLOWED_SYSCtls

if __name__ == "__main__":
    pass  # Example usage can go here if needed