"""Auto-generated by corpus2skill.py (Phase 3).

Theme: Kubernetes pod security standards
Source chunks: 1
Source URLs:
- https://kubernetes.io/docs/concepts/security/pod-security-standards/
Generated: 2026-05-31T23:55:51
Model: deepseek-r1:14b

Do not edit by hand; rerun corpus2skill.py to regenerate.
"""

"""
Kubernetes Pod Security Standards Helper Module

This module provides utility functions to validate Kubernetes pod security standards based on:
- Seccomp profile configurations
- Sysctl restrictions

Functions:
 - is_seccomp_profile_compliant(pod): Validates seccomp profiles for containers, initContainers, and ephemeralContainers
 - are_sysctls_compliant(sysctl_names): Validates sysctl names against allowed list
"""

from typing import Set, Optional, Dict

# Constants
ALLOWED_SECCOMP_TYPES: Set[str] = {'RuntimeDefault', 'Localhost'}
ALLOWED_SYSCTLS: Set[str] = {
    'kernel.shm_rmid_forced',
    'net.ipv4.ip_local_port_range',
    'net.ipv4.ip_unprivileged_port_start',
    'net.ipv4.tcp_syncookies',
    'net.ipv4.ping_group_range',
    'net.ipv4.ip_local_reserved_ports',
    'net.ipv4.tcp_keepalive_time',
    'net.ipv4.tcp_fin_timeout',
    'net.ipv4.tcp_keepalive_intvl',
    'net.ipv4.tcp_keepalive_probes'
}

def is_seccomp_profile_compliant(pod: Dict) -> bool:
    """
    Validate seccomp profiles for containers, initContainers, and ephemeralContainers.

    Args:
        pod: Kubernetes Pod specification dictionary

    Returns:
        bool: True if all containers have valid seccomp profiles, False otherwise
    """
    components = [
        pod.get('spec', {}).get('containers', []),
        pod.get('spec', {}).get('initContainers', []),
        pod.get('spec', {}).get('ephemeralContainers', [])
    ]
    
    for component in components:
        for container in component:
            seccomp_type: Optional[str] = container.get('securityContext', {}).get('seccompProfile', {}).get('type')
            if seccomp_type not in ALLOWED_SECCOMP_TYPES and seccomp_type is not None:
                return False
    return True

def are_sysctls_compliant(sysctl_names: Set[str]) -> bool:
    """
    Validate sysctl names against allowed list.

    Args:
        sysctl_names: Set of sysctl names to validate

    Returns:
        bool: True if all sysctl names are allowed, False otherwise
    """
    return sysctl_names.issubset(ALLOWED_SYSCTLS)