"""Auto-generated by corpus2skill.py (Phase 3).

Theme: Python asyncio best practices
Source chunks: 4
Source URLs:
- https://dev.to/shehzan/mastering-python-async-patterns-a-complete-guide-to-asyncio-in-2026-10o6
- https://discuss.python.org/t/asyncio-best-practices/12576
Generated: 2026-05-31T18:15:38
Model: deepseek-r1:14b

Do not edit by hand; rerun corpus2skill.py to regenerate.
"""

"""
Helper functions for common asyncio patterns and best practices.

This module provides reusable functions that implement key asyncio patterns,
such as handling concurrent requests, batch processing, and proper async client
setup. The goal is to make it easier to write clean, efficient, and maintainable
asyncio code.
"""

import asyncio
from contextlib import contextmanager
from typing import Any, AsyncIterator, List, Optional

@contextmanager
async def async_client_context(client_class: type, timeout: float = 10.0) -> AsyncIterator[Any]:
    """Create and manage an async client instance with specified timeout.

    Args:
        client_class: The async client class to instantiate (e.g., httpx.AsyncClient)
        timeout: Optional timeout value for the client

    Returns:
        An async context manager that yields the client instance
    """
    async with client_class(timeout=timeout) as client:
        yield client

async def batch_request_handler(
    urls: List[str],
    client: Any,
    batch_size: int = 50,
    rate_limit_interval: float = 1.0
) -> List[Any]:
    """Process URLs in batches to handle concurrency and rate limiting.

    Args:
        urls: List of URLs to process
        client: Async client instance (e.g., httpx.AsyncClient)
        batch_size: Number of requests per batch
        rate_limit_interval: Seconds to wait between batches

    Returns:
        List of results from processing all URLs
    """
    results = []
    for i in range(0, len(urls), batch_size):
        batch = urls[i:i+batch_size]
        batch_tasks = [scrape_page(client, url) for url in batch]
        batch_results = await asyncio.gather(*batch_tasks)
        results.extend(batch_results)
        await asyncio.sleep(rate_limit_interval)
    return results

async def async_function_wrapper(func: callable, *args, **kwargs) -> Any:
    """Execute an async function and handle the event loop.

    This is useful for wrapping async functions that need to be called from
    synchronous code or CLI scripts.

    Args:
        func: The async function to execute
        *args: Positional arguments for the function
        **kwargs: Keyword arguments for the function

    Returns:
        Result of the async function
    """
    return await asyncio.run(func(*args, **kwargs))

def parallel_execution(tasks: List[callable]) -> Any:
    """Execute multiple coroutines in parallel using asyncio.gather.

    This is a convenience wrapper around asyncio.gather to handle the event loop.

    Args:
        tasks: List of coroutine objects or callables

    Returns:
        Result(s) from executing the tasks
    """
    return asyncio.run(asyncio.gather(*tasks))

def sequential_execution(tasks: List[callable], progress_callback: Optional[callable] = None) -> Any:
    """Execute coroutines sequentially with optional progress feedback.

    Args:
        tasks: List of coroutine objects or callables
        progress_callback: Optional function to call after each task completes

    Returns:
        Result(s) from executing the tasks
    """
    loop = asyncio.get_event_loop()
    results = []
    for i, task in enumerate(tasks):
        result = loop.run_until_complete(task())
        results.append(result)
        if progress_callback:
            progress_callback(i + 1, len(tasks))
    return results

if __name__ == "__main__":
    # Example usage demonstration
    import httpx

    async def example_usage():
        urls = [f"https://example.com/page/{i}" for i in range(500)]
        client = httpx.AsyncClient()
        results = batch_request_handler(urls, client)
        return results

    print(async_function_wrapper(example_usage()))