"""Auto-generated by corpus2skill.py (Phase 3).

Theme: Python asyncio best practices
Source chunks: 4
Source URLs:
- https://dev.to/shehzan/mastering-python-async-patterns-a-complete-guide-to-asyncio-in-2026-10o6
- https://discuss.python.org/t/asyncio-best-practices/12576
Generated: 2026-05-31T19:33:17
Model: deepseek-r1:14b

Do not edit by hand; rerun corpus2skill.py to regenerate.
"""

"""
Python Asyncio Best Practices
This module provides reusable helper functions for working with asyncio, including:
- Concurrency controls
- Batch processing utilities
- HTTP client management
"""

import asyncio
from typing import Any, Sequence, Callable, Union
import httpx


async def gather_with_concurrency(tasks: Sequence[Callable], concurrency_limit: int = 10) -> list[Any]:
    """
    Run tasks concurrently with a limit on the number of simultaneous tasks.
    Returns results in the order they were received.
    """
    if not tasks:
        return []
    
    results = []
    task_batches = [tasks[i:i+concurrency_limit] for i in range(0, len(tasks), concurrency_limit)]
    
    for batch in task_batches:
        batch_results = await asyncio.gather(*batch)
        results.extend(batch_results)
        
    return results


async def async_batch_request(urls: Sequence[str], client_func: Callable[[], httpx.AsyncClient]) -> list[Any]:
    """
    Make concurrent HTTP requests with rate limiting and proper resource management.
    Takes a function that returns an AsyncClient instance.
    Returns list of responses in the order of input URLs.
    """
    client = await client_func()
    results = []
    
    for i in range(0, len(urls), 50):
        batch = urls[i:i+50]
        async with client:
            batch_results = await asyncio.gather(
                *[client.get(url) for url in batch]
            )
            results.extend(batch_results)
            await asyncio.sleep(1)  # Rate limiting
        
    return [r.json() for r in results]


async def measure_async_task_latency(func: Callable, *args, **kwargs) -> tuple[Any, float]:
    """
    Measure the latency of an async function.
    Returns (result, elapsed_time_in_seconds).
    """
    start = asyncio.get_event_loop().time()
    result = await func(*args, **kwargs)
    end = asyncio.get_event_loop().time()
    return result, end - start


if __name__ == "__main__":
    pass